name: ✨ Feature Request
description: Suggest a new feature or enhancement for the MUTHUR Terminal
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve the MUTHUR Terminal? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this feature solve? Is this related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the application does this relate to?
      options:
        - Boot Sequence
        - Terminal / Chat Interface
        - AI Responses (MUTHUR persona)
        - CRT Visual Effects
        - API / Backend
        - Deployment / Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, screenshots, or references that help illustrate the idea.
